[package]
name = "wayfinder-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.86"
quote = "1.0.36"
strum = "0.26.3"
strum_macros = "0.26.4"
syn = { version = "2.0.72", features = ["extra-traits"] }
